# [Choice] .NET version: 8.0, 8.0-bookworm-slim, 8.0-jammy
ARG VARIANT="8.0-jammy"
FROM mcr.microsoft.com/dotnet/sdk:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
